---
title: "Spotify Data Analysis"
author: 
- "Mencius Qin, Rachel Hyeon"
- 'Style Guide: tidyverse style guide'
output:
  pdf_document:
    toc: yes
  html_document:
    code_folding: show
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading, include=FALSE}
# Import libraries
library(tidyverse)
library(factoextra)
library(ggridges)
library(GGally)

# Load data
spotify <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv') %>% na.omit()
```

# Abstract:



# Introduction:



# Data:

```{r gg-pairs}
spotify %>% ggpairs(columns = 12:23,
                    mapping = aes(alpha = .5))
```

```{r}
spotify_cor <- cor(spotify[, -c(1:3, 5:11)], method = "pearson")
```

```{r, fig.height=7, fig.width=7, fig.cap="Correlation matrix"}
corrplot::corrplot(spotify_cor, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45, diag = F, tl.cex = 0.5)
```

As we see in the correlation matrix, the `energy:loudness` pair and `energy:acousticness` pair seems to be correlated, following by the `loudness:acousticness` pair and `danceability:valence` pair.

```{r genre-popularity}
# Graph code
genre_ridgeline <- spotify %>%
  ggplot(aes(x = track_popularity, 
             y = playlist_genre,
             height = stat(density),
             fill = playlist_genre)) +
  geom_density_ridges(stat = "density") +
  theme_bw() +
  labs(x = "Popularity of the Song", y = "Genre",
       title = "Ridgeline plot of Song Popularity of different Genre
               (All Genre contains a mode of low popularity)")

plot(genre_ridgeline)
```

```{r pca-analysis}
spotify_quant <- spotify[, c(4, 12:13, 15, 17:23)]

spotify_pca <- prcomp(dplyr::select(spotify_quant, danceability:duration_ms),
                     center = TRUE, scale. = TRUE)
summary(spotify_pca)
```

```{r scree-plot}
fviz_eig(spotify_pca, addlabels = TRUE, ncp = 10) +
  geom_hline(yintercept = 100 * (1 / ncol(spotify_pca$x)), 
             linetype = "dashed", color = "red")
```

```{r pop-pca}
spotify_pc_matrix <- spotify_pca$x

pop_pca_df <- spotify %>% 
  mutate(pc1 = spotify_pc_matrix[,1], pc2 = spotify_pc_matrix[,2])
pop_pca <- pop_pca_df %>%
  ggplot(aes(x = pc1, y = pc2)) +
  geom_point(aes(color = track_popularity), alpha = 0.5) +
  scale_colour_gradient(low = "white", high = "orange") +
  theme_bw() +
  labs(x = "PC 1", y = "PC 2", color = "Track Popularity")

plot(pop_pca)
```

```{r pop-biplot}
fviz_pca_biplot(spotify_pca,
                # Plot PC1 and PC3
                axes = c(1, 2), label = "var",
                # Change the alpha for the observations - 
                # which is represented by ind
                alpha.ind = .25,
                # Modify the alpha for the variables (var):
                alpha.var = .5,
                repel = TRUE,
                # Set the color of the points to decades variable:
                col.ind = pop_pca_df$track_popularity, 
                # Modify the color of the variables
                col.var = "darkblue") +
   scale_color_gradient(low = "white", high = "darkorange") +
   labs(color = "Track Popularity") +
   theme(legend.position = "bottom")
```

```{r pop-heat}
pop_heat <- spotify %>% 
  ggplot(aes(x = loudness, y = instrumentalness)) +
  stat_density2d(geom = "tile", contour = FALSE) +
  geom_point(aes(color = track_popularity), alpha = .2) + 
  scale_color_gradient(low = "lightblue", high = "orange") +
  theme_bw() + 
  labs(title = "Heat Map")

plot(pop_heat)
```

```{r spotify-100}
spotify_100 <- spotify %>% 
  arrange(-track_popularity) %>% 
  top_n(150, track_popularity)
```

```{r genre-100}
bar_100 <- spotify_100 %>% 
  ggplot(aes(x = playlist_genre, fill = playlist_subgenre)) +
  geom_bar(position = "dodge")

plot(bar_100)
```




# Methods:



# Results:



# Discussion:


